/**
 * This file is ALWAYS at the src/trackingEvents.d.ts path of every folder.
 *
 * It MUST NOT import any type.
 * It MUST export a TrackingEvents type with key->value mappings of tracking event types.
 *
 * This file will be statically analyzed to generate reports, please do follow the
 * suggestions in this comment.
 *
 * Changes to this file would require validation from the @decentraland/data-team
 * to prevent breaking reports
 **/

export type TrackingEvents = {
  /** when users click in "play" */
  open_login_popup: {}
  /** when a provider is selected to play */
  click_login_button: {
    provider_type: string
  }
  /** when the user disconnects */
  disconnection: {}
  /** explorer-website errors (react, sagas or loading components) */
  explorer_website_error: {
    error: string
  }
  /** when the app loads and connects the user automatically due to a stored session */
  automatic_relogin: {
    provider_type: string
  }
  /** disable analytics due to a fatal error */
  disable_analytics: {}
  /** enable renderer */
  enable_renderer: {}
  /** Send kernel, website and renderer versions */
  initialize_versions: Record<string, string>
}

export type SessionTraits = {
  // unique ID for each session. It is generated by the browser each time it starts
  sessionId: string
}
