name: Deployment Notification

on:
  pull_request:
    types: [opened]

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Decentraland Unity-Renderer Deployment Notification
    steps:
      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch
      - name: Comment PR
        if: ${{ github.event.pull_request.head.repo.full_name == 'decentraland/explorer-desktop-launcher' }} # Not a fork
        uses: thollander/actions-comment-pull-request@main
        with:
          message: |
            After the CI passes:

            This branch can be downloaded with the following links:
            - [Windows](https://renderer-artifacts.decentraland.org/launcher-branch/${{ steps.branch.outputs.branch_name }}/Install%20Decentraland.exe)
            - [Linux](https://renderer-artifacts.decentraland.org/launcher-branch/${{ steps.branch.outputs.branch_name }}/Decentraland.AppImage)
            - [Mac](https://renderer-artifacts.decentraland.org/launcher-branch/${{ steps.branch.outputs.branch_name }}/Decentraland.dmg)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
